title: Webkanini Technologies Pvt Ltd
description: "Helping businesses streamline operations with Odoo ERP and business software."
baseurl: ""       # keep empty for user/org site
url: "https://www.webkanini.com"
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed